# Generated by Django 4.1.3 on 2022-12-01 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import game_check.game_review.validators


class Migration(migrations.Migration):

    dependencies = [
        ('game_review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('age', models.PositiveIntegerField(validators=[game_check.game_review.validators.age_validator])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('DoNotShow', 'Do not show')], max_length=9)),
                ('avatar', models.ImageField(upload_to='avatars/', validators=[game_check.game_review.validators.validate_file_less_than_one])),
                ('bio', models.TextField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
