# Generated by Django 4.1.3 on 2022-12-01 12:07

from django.db import migrations, models
import game_check.game_review.validators


class Migration(migrations.Migration):

    dependencies = [
        ('game_review', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='game_images/', validators=[game_check.game_review.validators.validate_file_less_than_one])),
            ],
        ),
    ]
