# Generated by Django 4.1.3 on 2022-12-01 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_review', '0006_alter_gamecomment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_comment',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, to='game_review.gamecomment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='game_score',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, to='game_review.gamescore'),
            preserve_default=False,
        ),
    ]
