# Generated by Django 4.1.3 on 2022-12-01 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_review', '0008_gamefavourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_favourite',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, to='game_review.gamefavourite'),
            preserve_default=False,
        ),
    ]
