# Generated by Django 4.1.3 on 2022-12-03 08:10

from django.db import migrations, models
import game_check.game_review.validators


class Migration(migrations.Migration):

    dependencies = [
        ('game_review', '0010_siteuser_slug_alter_profile_avatar_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='./staticfiles/temp-default.jpg', upload_to='avatars/', validators=[game_check.game_review.validators.validate_file_less_than_one]),
        ),
    ]
