# Generated by Django 4.1.3 on 2022-12-03 09:35

from django.db import migrations, models
import game_check.game_review.validators


class Migration(migrations.Migration):

    dependencies = [
        ('game_review', '0011_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='avatars/', validators=[game_check.game_review.validators.validate_file_less_than_one]),
        ),
    ]
