# Generated by Django 4.1.3 on 2022-12-03 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_review', '0013_alter_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_comment',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_favourite',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_score',
        ),
        migrations.AddField(
            model_name='gamecomment',
            name='game',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, to='game_review.game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamefavourite',
            name='game',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, to='game_review.game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamescore',
            name='game',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, to='game_review.game'),
            preserve_default=False,
        ),
    ]
