# Generated by Django 4.1.3 on 2022-12-03 11:43

from django.db import migrations, models
import game_check.game_review.validators


class Migration(migrations.Migration):

    dependencies = [
        ('game_review', '0015_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(upload_to='game_images', validators=[game_check.game_review.validators.validate_file_less_than_one]),
        ),
    ]
