# Generated by Django 4.1.3 on 2022-12-05 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_review', '0017_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecomment',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='comments', to='game_review.game'),
        ),
    ]
