# Generated by Django 4.1.3 on 2022-12-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_review', '0019_game_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
