# Generated by Django 4.1.3 on 2022-12-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_review', '0020_siteuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default='2022-12-08'),
            preserve_default=False,
        ),
    ]
