# Generated by Django 4.1.3 on 2022-12-11 09:23

from django.db import migrations, models
import game_check.game_review.validators


class Migration(migrations.Migration):

    dependencies = [
        ('game_review', '0023_alter_game_options_gamecomment_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamecomment',
            options={'ordering': ('date_created',)},
        ),
        migrations.AlterField(
            model_name='gamecomment',
            name='content',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='gamefavourite',
            name='is_favourite',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='value',
            field=models.FloatField(validators=[game_check.game_review.validators.score_validator], verbose_name=''),
        ),
    ]
