# Generated by Django 4.1.3 on 2022-12-17 09:57

from django.db import migrations, models
import game_check.game_review.validators


class Migration(migrations.Migration):

    dependencies = [
        ('game_review', '0024_alter_gamecomment_options_alter_gamecomment_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecomment',
            name='content',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='gamefavourite',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='value',
            field=models.FloatField(validators=[game_check.game_review.validators.score_validator]),
        ),
    ]
